services:
  app:
    build:
      target: app-interactive
      args:
        LANG: "${LANG:-en_US.UTF-8}"
        TZ: 'America/New_York'
        UNMINIMIZE: true
        GIT_DEFAULT_BRANCH: master
        GIT_USER:
        GIT_EMAIL:
    environment:
      TERM: "${TERM}"
      # ZSH_THEME: robbyrussell
    volumes:
      # Source
      - ".:/var/www/html"
      # Dependencies
      - "app.composer:/var/www/html/vendor"
volumes:
  app.composer:
    driver: local
